package com.xypt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SynchronizeCompanyInfo", targetNamespace = "http://service.project.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SynchronizeCompanyInfo {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String uploadCompanyInfo(
			@WebParam(name = "arg0", partName = "arg0") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String searchCreditInfo(
			@WebParam(name = "arg0", partName = "arg0") String arg0);

}
