package com.xypt;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SynchronizeCompanyInfoService service = new SynchronizeCompanyInfoService();
 * SynchronizeCompanyInfo portType = service.getSynchronizeCompanyInfoPort();
 * portType.uploadCompanyInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SynchronizeCompanyInfoService", targetNamespace = "http://service.project.com/", wsdlLocation = "http://esb.sipac.gov.cn:5888/services/SynchronizeCompanyInfoPort?wsdl")
public class SynchronizeCompanyInfoService extends Service {

	private final static URL SYNCHRONIZECOMPANYINFOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.xypt.SynchronizeCompanyInfoService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.xypt.SynchronizeCompanyInfoService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://esb.sipac.gov.cn:5888/services/SynchronizeCompanyInfoPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://esb.sipac.gov.cn:5888/services/SynchronizeCompanyInfoPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SYNCHRONIZECOMPANYINFOSERVICE_WSDL_LOCATION = url;
	}

	public SynchronizeCompanyInfoService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SynchronizeCompanyInfoService() {
		super(SYNCHRONIZECOMPANYINFOSERVICE_WSDL_LOCATION, new QName(
				"http://service.project.com/", "SynchronizeCompanyInfoService"));
	}

	/**
	 * 
	 * @return returns SynchronizeCompanyInfo
	 */
	@WebEndpoint(name = "SynchronizeCompanyInfoPort")
	public SynchronizeCompanyInfo getSynchronizeCompanyInfoPort() {
		return super.getPort(new QName("http://service.project.com/",
				"SynchronizeCompanyInfoPort"), SynchronizeCompanyInfo.class);
	}

}
