package com.jshx.httpData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * USRCoreService service = new USRCoreService();
 * USRCoreServiceSoap portType = service.getUSRCoreServiceSoap();
 * portType.callDestService(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "USRCoreService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://122.193.30.10:9999/USRCoreService.asmx?wsdl")
public class USRCoreService extends Service {

	private final static URL USRCORESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.jshx.httpData.USRCoreService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.jshx.httpData.USRCoreService.class.getResource(".");
			url = new URL(baseUrl,
					"http://122.193.30.10:9999/USRCoreService.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://122.193.30.10:9999/USRCoreService.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USRCORESERVICE_WSDL_LOCATION = url;
	}

	public USRCoreService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public USRCoreService() {
		super(USRCORESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"USRCoreService"));
	}

	/**
	 * 
	 * @return returns USRCoreServiceSoap
	 */
	@WebEndpoint(name = "USRCoreServiceSoap")
	public USRCoreServiceSoap getUSRCoreServiceSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"USRCoreServiceSoap"), USRCoreServiceSoap.class);
	}

	/**
	 * 
	 * @return returns USRCoreServiceSoap
	 */
	@WebEndpoint(name = "USRCoreServiceSoap12")
	public USRCoreServiceSoap getUSRCoreServiceSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"USRCoreServiceSoap12"), USRCoreServiceSoap.class);
	}

}
