package com.jshx.httpData;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "USRCoreServiceSoap", targetNamespace = "http://tempuri.org/")
public interface USRCoreServiceSoap {

	/**
	 * 
	 * @param xmlPage
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CallDestService", action = "http://tempuri.org/CallDestService")
	@WebResult(name = "CallDestServiceResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CallDestService", targetNamespace = "http://tempuri.org/", className = "com.jshx.httpData.CallDestService")
	@ResponseWrapper(localName = "CallDestServiceResponse", targetNamespace = "http://tempuri.org/", className = "com.jshx.httpData.CallDestServiceResponse")
	public String callDestService(
			@WebParam(name = "XMLPage", targetNamespace = "http://tempuri.org/") String xmlPage);

	/**
	 * 
	 * @param strLoginID
	 * @param strPwd
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CallAuthenticate", action = "http://tempuri.org/CallAuthenticate")
	@WebResult(name = "CallAuthenticateResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CallAuthenticate", targetNamespace = "http://tempuri.org/", className = "com.jshx.httpData.CallAuthenticate")
	@ResponseWrapper(localName = "CallAuthenticateResponse", targetNamespace = "http://tempuri.org/", className = "com.jshx.httpData.CallAuthenticateResponse")
	public String callAuthenticate(
			@WebParam(name = "strLoginID", targetNamespace = "http://tempuri.org/") String strLoginID,
			@WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/") String strPwd);

}
