
package com.lkdj.frk;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "frjcPortService", targetNamespace = "http://sipac/lk/lk-producing-web-service", wsdlLocation = "http://esb.sipac.gov.cn:5888/services/FRJCInsertN?wsdl")
public class FrjcPortService
    extends Service
{

    private final static URL FRJCPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lkdj.frk.FrjcPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lkdj.frk.FrjcPortService.class.getResource(".");
            url = new URL(baseUrl, "http://esb.sipac.gov.cn:5888/services/FRJCInsertN?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://esb.sipac.gov.cn:5888/services/FRJCInsertN?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FRJCPORTSERVICE_WSDL_LOCATION = url;
    }

    public FrjcPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrjcPortService() {
        super(FRJCPORTSERVICE_WSDL_LOCATION, new QName("http://sipac/lk/lk-producing-web-service", "frjcPortService"));
    }

    /**
     * 
     * @return
     *     returns FrjcPort
     */
    @WebEndpoint(name = "frjcPortSoap11")
    public FrjcPort getFrjcPortSoap11() {
        return super.getPort(new QName("http://sipac/lk/lk-producing-web-service", "frjcPortSoap11"), FrjcPort.class);
    }

}
