
package com.lkdj.frk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "frjcPort", targetNamespace = "http://sipac/lk/lk-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FrjcPort {


    /**
     * 
     * @param getFRJCInsertRequest
     * @return
     *     returns com.lkdj.frk.GetFRJCInsertResponse
     */
    @WebMethod
    @WebResult(name = "getFRJCInsertResponse", targetNamespace = "http://sipac/lk/lk-producing-web-service", partName = "getFRJCInsertResponse")
    public GetFRJCInsertResponse getFRJCInsert(
        @WebParam(name = "getFRJCInsertRequest", targetNamespace = "http://sipac/lk/lk-producing-web-service", partName = "getFRJCInsertRequest")
        GetFRJCInsertRequest getFRJCInsertRequest);

}
