
package com.lkdj.kzk;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* tkzxxPortService service = new tkzxxPortService();
* TkzxxPort portType = service.getTkzxxPortSoap11();
* portType.getTkzxx(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "tkzxxPortService", targetNamespace = "http://sipac/lk/lk-producing-web-service", wsdlLocation = "http://esb.sipac.gov.cn:5888/services/KZXXInsertN?wsdl")
public class TkzxxPortService
    extends Service
{

    private final static URL TKZXXPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lkdj.kzk.TkzxxPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lkdj.kzk.TkzxxPortService.class.getResource(".");
            url = new URL(baseUrl, "http://esb.sipac.gov.cn:5888/services/KZXXInsertN?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://esb.sipac.gov.cn:5888/services/KZXXInsertN?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TKZXXPORTSERVICE_WSDL_LOCATION = url;
    }

    public TkzxxPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TkzxxPortService() {
        super(TKZXXPORTSERVICE_WSDL_LOCATION, new QName("http://sipac/lk/lk-producing-web-service", "tkzxxPortService"));
    }

    /**
     * 
     * @return
     *     returns TkzxxPort
     */
    @WebEndpoint(name = "tkzxxPortSoap11")
    public TkzxxPort getTkzxxPortSoap11() {
        return super.getPort(new QName("http://sipac/lk/lk-producing-web-service", "tkzxxPortSoap11"), TkzxxPort.class);
    }

}
