
package com.lkdj.kzk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "tkzxxPort", targetNamespace = "http://sipac/lk/lk-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TkzxxPort {


    /**
     * 
     * @param getTkzxxRequest
     * @return
     *     returns com.lkdj.kzk.GetTkzxxResponse
     */
    @WebMethod
    @WebResult(name = "getTkzxxResponse", targetNamespace = "http://sipac/lk/lk-producing-web-service", partName = "getTkzxxResponse")
    public GetTkzxxResponse getTkzxx(
        @WebParam(name = "getTkzxxRequest", targetNamespace = "http://sipac/lk/lk-producing-web-service", partName = "getTkzxxRequest")
        GetTkzxxRequest getTkzxxRequest);

}
