
package com.lkdj.rkk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "lkrekouPort", targetNamespace = "http://sipac/lk/lk-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LkrekouPort {


    /**
     * 
     * @param getLkRKRequest
     * @return
     *     returns com.lkdj.rkk.GetLkRKResponse
     */
    @WebMethod
    @WebResult(name = "getLkRKResponse", targetNamespace = "http://sipac/lk/lk-producing-web-service", partName = "getLkRKResponse")
    public GetLkRKResponse getLkRK(
        @WebParam(name = "getLkRKRequest", targetNamespace = "http://sipac/lk/lk-producing-web-service", partName = "getLkRKRequest")
        GetLkRKRequest getLkRKRequest);

}
