
package com.lkdj.rkk;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* lkrekouPortService service = new lkrekouPortService();
* LkrekouPort portType = service.getLkrekouPortSoap11();
* portType.getLkRK(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "lkrekouPortService", targetNamespace = "http://sipac/lk/lk-producing-web-service", wsdlLocation = "http://esb.sipac.gov.cn:5888/services/RKJCInsertN?wsdl")
public class LkrekouPortService
    extends Service
{

    private final static URL LKREKOUPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lkdj.rkk.LkrekouPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lkdj.rkk.LkrekouPortService.class.getResource(".");
            url = new URL(baseUrl, "http://esb.sipac.gov.cn:5888/services/RKJCInsertN?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://esb.sipac.gov.cn:5888/services/RKJCInsertN?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LKREKOUPORTSERVICE_WSDL_LOCATION = url;
    }

    public LkrekouPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LkrekouPortService() {
        super(LKREKOUPORTSERVICE_WSDL_LOCATION, new QName("http://sipac/lk/lk-producing-web-service", "lkrekouPortService"));
    }

    /**
     * 
     * @return
     *     returns LkrekouPort
     */
    @WebEndpoint(name = "lkrekouPortSoap11")
    public LkrekouPort getLkrekouPortSoap11() {
        return super.getPort(new QName("http://sipac/lk/lk-producing-web-service", "lkrekouPortSoap11"), LkrekouPort.class);
    }

}
